### DISCUSSION TITLE
Micronaut Data  Multitenancy for JDBC

### DISCUSSION THREAD

**Discussion by tatapia** [micronaut-projects/micronaut-data#1648] [Q&A]
Hello, 

I would like to request some guidance or workaround to implement multi-tenancy like database-per-tenant for JDBC datasources, I am aware that something like "GORM-style" is not ready yet (until next major Micronaut-Data release). So, how can I achieve this programmatically? Im not sure where to start, so any recommendations will be really appreciated. 

FYI: I cannot make use of Hibernate/JPA or GORM

This is my idea:

I will have all my datasources specified in my _application.yml_ 

```
datasources:
  default:
    url: jdbc:oracle:thin:@db1?TNS_ADMIN=path/to/db1/wallet
    username: $$$$$$$$$
    password: $$$$$$$$$
  fastlane:
    url: jdbc:oracle:thin:@db2?TNS_ADMIN=path/to/db2/wallet
    username: $$$$$$$$$
    password: $$$$$$$$$
    
```
And then when making a Request to my service, some class will intercept the request and solve the tenant with HttpHeaderTenantResolver, in this case, the tenant will represent the name of the datasource to be triggered (default or fastlane) and finally after the correct datasource was selected, the request can be sent to the proper datasource.

Thanks for your help.
