### DISCUSSION TITLE
is possible to configure Hikari to manage R2DBC connections?

### DISCUSSION THREAD

**Discussion by lucasgust** [micronaut-projects/micronaut-data#2448] [Q&A] [answered]
**[CONTEXT]**
I'm developing an application (with Kotlin and Gradle) and I want to use R2DBC and Hikari to manage database connection pool.
I exposed an API which simulates an insert into two different tables and this execution must be done inside a transaction.

```kotlin
// repositories
@R2dbcRepository(dialect = MYSQL)
interface EmployeeRepository :
    CoroutineCrudRepository<Employee, Long>,
    CoroutineJpaSpecificationExecutor<Employee> {

    @Transactional(propagation = TransactionDefinition.Propagation.MANDATORY)
    override suspend fun <S : Employee> save(entity: S): S
}

@R2dbcRepository(dialect = MYSQL)
interface ExternalEmployeeRepository :
    CoroutineCrudRepository<ExternalEmployee, ExternalEmployeeId>,
    CoroutineJpaSpecificationExecutor<ExternalEmployee> {

    @Transactional(propagation = TransactionDefinition.Propagation.MANDATORY)
    override suspend fun <S : ExternalEmployee> save(entity: S): S
}

// service
@Singleton
open class CreateEmployeeUseCase(
    private val createEmployeeService: CreateEmployeeService, // inject EmployeeRepository and save data
    private val createExternalEmployeeService: CreateExternalEmployeeService // inject ExternalEmployeeRepository and save data
) : CreateEmployeePort {

    @Transactional
    override suspend fun create(employee: Employee) =
        createEmployeeService.create(employee)
            .also { createExternalEmployeeService.create(it) }
}
```

```yml
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true

datasources:
  default:
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    schema-generate: NONE
    url: jdbc:mysql://localhost:3306/txwithr2dbc
    username: root
    password: root
    db-type: mysql

r2dbc:
  datasources:
    default:
      schema-generate: NONE
      url: r2dbc:mysql://localhost:3306/txwithr2dbc
      username: root
      password: root
      dialect: MYSQL
      driver: mysql
      db-type: mysql
```

**[ERROR]**
when I call this API (which invokes `CreateEmployeeUseCase.create`) I receive this error:
```
io.micronaut.context.exceptions.ConfigurationException: No reactive transaction management has been configured. Ensure you have correctly configured a async capable transaction manager
```

OK, it's understandable because Hikari is using a JDBC connection as the initial log points out...
```
INFO HikariDataSource - HikariPool-1 - Starting...
INFO HikariPool - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@5f2afe62
INFO HikariDataSource - HikariPool-1 - Start completed.
INFO AbstractFlywayMigration - Running migrations for database with qualifier [default]
```

**[SOLUTIONS]**
...and I fixed this
1) by removing Hikari dependency from project; or
2) by giving a different dataSource name for `r2dbc` configuration and setting it in repositories (`@R2dbcRepository(dataSource = "other-name"`)

**[QUESTION]**
following solution number 2, I understand that R2DBC connections would not be managed by Hikari, right? if i'm right, is there a way to do this? if not, is it recommended to go without Hikari?
