### DISCUSSION TITLE
how to configure test resources with Flyway and R2DBC using different datasources?

### DISCUSSION THREAD

**Discussion by lucasgust** [micronaut-projects/micronaut-data#2450] [Q&A] [answered]
as suggested in [this discussion](https://github.com/micronaut-projects/micronaut-data/discussions/2448) I'm using R2DBC as datasource `default` and JDBC/Flyway as `migration` to avoid transaction issues not being created within a reactive context.

now the problem is my integration tests because the test resources try to look for a `migrate` datasource inside `r2dbc` (and there is none).

PROJECT --> https://github.com/lucasgust/txwithr2dbc

I'm managed to implement a workaround but I'm feeling that's not the right way to do this.

```yml
flyway:
  datasources:
    migration:
      enabled: true

datasources:
  migration:
    db-type: mysql

r2dbc:
  datasources:
    migration:
      db-type: mysql
    default:
      db-type: mysql
      url: ${r2dbc.datasources.migration.url} --> need to reuse this url because test resources creates a new instance (different port) for each new datasource name
      username: ${r2dbc.datasources.migration.username}
      password: ${r2dbc.datasources.migration.password}
```

is there another way to achieve this?

**Comment by dstepanov** [comment, marked as answer]
I guess it's not possible with Test Resources. The only way is to have it named `default`. Please check this guide https://micronaut-projects.github.io/micronaut-r2dbc/1.0.x/guide/

**Reply by lucasgust** [reply]
@dstepanov thanks for your response. my workaround works but I thought there is an easier way...

**Reply by dstepanov** [reply]
What workaround is that?

**Reply by lucasgust** [reply]
this configuration I mentioned above, it's what I'm using in test environment:

```
r2dbc:
  datasources:
    migration:
      db-type: mysql
    default:
      db-type: mysql
      url: ${r2dbc.datasources.migration.url}
      username: ${r2dbc.datasources.migration.username}
      password: ${r2dbc.datasources.migration.password}
```
