### ISSUE TITLE
support creation of schema DDL script from application configuration 

### ISSUE THREAD

**Issue by rosemead** [micronaut-projects/micronaut-data#1175]
### Feature description

Hi. 
JPA provides `create-target` configuration to create a schema DDL script. spring boot supports this config through its `application.properties` (`spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target`). Think [quarkus](https://github.com/quarkusio/quarkus/issues/14771) does too? 

Can this be done in micronaut? via `application.yml`?

**Comment by graemerocher** [comment]
Does `jpa.default.properties.javax.persistence.schema-generation.scripts.create-target` not work?

**Comment by rosemead** [comment]
Could not get it to work. Tried adding it on-top of the [JPA guide app](https://guides.micronaut.io/latest/micronaut-jpa-hibernate-maven-java.zip). did a 'mvn mn:run'. No sql generated.

**Comment by mstein** [comment]
Using this in the `application.yml` : 
```yaml
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
jpa:
  default:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              create-target: createFile.ddl
              drop-target: dropFile.ddl
```
And running the app (through gradle, but I don't think the build tool matter) does generate the ddl files for me.
Using Micronaut 3.0.1 and Micronaut-data (hibernate-jpa) 3.0.1.

**Comment by mstein** [comment]
I just tested with the jpa guide app you have linked, and it also seems to work on my side.
I changed the jpa config in the `application.yml` to this : 
```yaml
---
#tag::jpa[]
jpa:
  default:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              create-target: createFile.ddl
              drop-target: dropFile.ddl
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
#end::jpa[]
```
And after running `./mvnw mn:run`, the ddl files are generated in the `target` folder.
