### ISSUE TITLE
micronaut-data-r2dbc does not recognize a schema built from a hikari datasource and flyway

### ISSUE THREAD

**Issue by rawilder** [micronaut-projects/micronaut-data#1456]
### Expected Behavior

When a schema is specified in the configuration, r2dbc should search it for the table definitions.

### Actual Behaviour

When a schema is specified, r2dbc repositories fail to find the tables on the specified schema, instead searching the default (public for postgres)

### Steps To Reproduce

1. Make a micronaut project with data-r2dbc, flyway, postgres, jdbc-hikari
2. Create an entity and flyway migration for it
3. Add datasources for flyway and jdbc-hikari (necessary for flyway to work)
4. Try to query with an r2dbc repository
5. Observe the query fail

The branch linked below has tests showing this happening.

### Environment Information

jdk 11 amazon corretto
macos 12.3.1

### Example Application

https://github.com/rawilder/r2dbc-dto-projections/tree/r2dbc-postgres-schema-issue

### Version

3.4.2

**Comment by rawilder** [comment]
Foolish of me, schema isn't specified explicitly but through `options`
```
r2dbc:
  datasources:
    default:
      url: placeholder
      username: placeholder
      password: placeholder
      options:
        schema: custom_schema

```
