### ISSUE TITLE
Wrongly marking columns as not null, wrong type, wrong varchar size

### ISSUE THREAD

**Issue by tivrfoa** [micronaut-projects/micronaut-data#1597]
### Expected Behavior

It's defined in the Flyway schema as:

```sql
DROP TABLE IF EXISTS genre;

CREATE TABLE genre (
    id   BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    name  VARCHAR(255) NOT NULL UNIQUE,
    value decimal(6, 2),
    country varchar(30) default ''
);
```

```java
package com.example;

import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;

import javax.validation.constraints.NotNull;

@MappedEntity
public class Genre {

    @Id
    @GeneratedValue(GeneratedValue.Type.AUTO)
    private Long id;

    @NotNull
    private String name;

    private double value;

    private String country;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Override
    public String toString() {
        return "Genre [id=" + id + ", name=" + name + ", value=" + value + ", country=" + country + "]";
    }
}
```

### Actual Behaviour

```sql
[main] DEBUG io.micronaut.data.query - Executing CREATE statement: 

CREATE TABLE `genre` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT,`name` VARCHAR(255) NOT NULL,`value` DOUBLE NOT NULL,`country` VARCHAR(255) NOT NULL);
```

### Version

3.5.2

**Comment by dstepanov** [comment]
It looks like the schema is generated using the Micronaut Data Schema generator instead of Flyway. There is something incorrectly configured.

**Comment by tivrfoa** [comment]
> It looks like the schema is generated using the Micronaut Data Schema generator instead of Flyway. There is something incorrectly configured.

I followed this tutorial:
https://guides.micronaut.io/latest/micronaut-data-jdbc-repository-maven-java.html

**Comment by tivrfoa** [comment]
application.yml

```yml
micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut
    driverClassName: com.mysql.cj.jdbc.Driver
    username: aaa
    password: '123'
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
```
