### ISSUE TITLE
It creates column with type Date, but should be Time

### ISSUE THREAD

**Issue by tivrfoa** [micronaut-projects/micronaut-data#1598]
### Expected Behavior

Create column with type Time

	@MappedProperty (value = "wakeup_time")
	private Time wakeUpTime;

### Actual Behaviour

```txt
mysql> desc person;
+----------------+--------------+------+-----+----------------------+-------------------+
| Field          | Type         | Null | Key | Default              | Extra             |
+----------------+--------------+------+-----+----------------------+-------------------+
| id             | int          | NO   |     | NULL                 |                   |
| wakeup_time    | date         | NO   |     | NULL                 |                   |
+----------------+--------------+------+-----+----------------------+-------------------+
```

### Steps To Reproduce

application.yml

```yml
micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut
    driverClassName: com.mysql.cj.jdbc.Driver
    username: aaa
    password: '123'
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
```

### Version

3.5.2
