### ISSUE TITLE
Entities not found for JPA Configuration in Kotlin Service

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-data#2157]
### Discussed in https://github.com/micronaut-projects/micronaut-data/discussions/2156

<div type='discussions-op-text'>

<sup>Originally posted by **lacerdanycolas** April 28, 2023</sup>
Hi,

I configured a microservice with micronaut-data-hibernate-jpa and when start the container locally it shows the following error: "Entities not found for JPA Configuration: default with package 'my.app.package'. Also tested add `@Introspected` annotation in my App.kt with the same package present in application.yml and doesnt work too

**Entity.kt**
```
import my.app.package

@Entity
@Table(name = "my_table")
class EntityTest()
```

**Application.yml**
```
datasources:
   default:
     url: {my.url.db}
     username: {my.username.db}
     password:: {my.password.db}
     dialect: POSTGRES
     db-type: postgres
     driver-class-name: org.postgresql.Driver
jpa
   default
      packages-to-scan:
          - 'my.app.package' 
```

**Pom.xml**
```
...
<dependency>
    <groupId>io.micronaut.data</groupId>
    <artifactId>micronaut-data-hibernate-jpa</artifactId>
    <version>3.9.6</version>
</dependency>
<dependency>
    <groupId>io.micronaut.sql</groupId>
    <artifactId>micronaut-jdbc-hikari</artifactId>
    <version>4.7.2</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>42.4.3</version>
</dependency>
...

```

How can I fix this problem? Thanks for suport 
</div>
